### ISSUE TITLE
Improve the Logging, do not create more than 10 instances (reuse them)

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#166]
In order to avoid this warning:

(node:29647) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at process.addListener (node:events:606:10)
    at ExceptionHandler.handle (/home/ubuntu/ocean-node/node_modules/winston/lib/winston/exception-handler.js:51:15)
    at DerivedLogger.configure (/home/ubuntu/ocean-node/node_modules/winston/lib/winston/logger.js:145:23)
    at new Logger (/home/ubuntu/ocean-node/node_modules/winston/lib/winston/logger.js:42:10)
    at new DerivedLogger (/home/ubuntu/ocean-node/node_modules/winston/lib/winston/create-logger.js:44:7)
    at module.exports [as createLogger] (/home/ubuntu/ocean-node/node_modules/winston/lib/winston/create-logger.js:48:18)
    at new CustomNodeLogger (file:///home/ubuntu/ocean-node/dist/utils/logging/Logger.js:165:35)
    at getCustomLoggerForModule (file:///home/ubuntu/ocean-node/dist/utils/logging/Logger.js:233:20)
{

related thread:
https://stackoverflow.com/questions/58653678/winston-maxlistenersexceededwarning-possible-eventemitter-memory-leak-detecte
https://github.com/winstonjs/winston/blob/f707f337122ad629aa1033ff935fe1b5e9aed170/lib/winston/exception-handler.js#L40-L53

we should not create more instances of the logger than needed (10 should be enough).

**Comment by paulo-ocean** [comment]
closed on https://github.com/oceanprotocol/ocean-node/pull/178
