### ISSUE TITLE
Encrypt endpoint failure

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#251]
I was introducing TVL guys to ocean-node and stumble into:

```bash
georgevlada@Georges-MacBook-Pro ocean-cli % npm run cli publish metadata/simpleDownloadDataset.json
> ocean-cli@2.0.0 cli
> ./node_modules/ts-node/dist/bin.js src/index.ts publish metadata/simpleDownloadDataset.json
Using RPC: https://rpc-mumbai.maticvigil.com/
Using account: 0xA15b176636327cc45505BAaF89cDD6c4B003594b
Using Provider : http://localhost:8000/
Using Aquarius : http://localhost:8000/
start publishing
Error validating metadata:  FetchError: invalid json response body at http://localhost:8000//api/aquarius/assets/ddo/validate reason: Unexpected token < in JSON at position 0
    at /Users/georgevlada/projects/ocean-cli/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: ‘invalid-json’
}
Error when publishing dataset from file: metadata/simpleDownloadDataset.json
Error: invalid arrayify value (argument=“value”, value=“<!DOCTYPE html>\n<html lang=\“en\“>\n<head>\n<meta charset=\“utf-8\“>\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST //api/services/encrypt</pre>\n</body>\n</html>\n”, code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at arrayify (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/bytes/src.ts/index.ts:141:19)
    at BytesCoder.DynamicBytesCoder.encode (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/abi/src.ts/coders/bytes.ts:17:25)
    at /Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/abi/src.ts/coders/array.ts:62:19
    at Array.forEach (<anonymous>)
    at pack (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
    at TupleCoder.encode (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:54:20)
    at AbiCoder.encode (/Users/georgevlada/projects/ocean-cli/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:111:15) {
  reason: ‘invalid arrayify value’,
  code: ‘INVALID_ARGUMENT’,
  argument: ‘value’,
  value: ‘<!DOCTYPE html>\n’ +
    ‘<html lang=“en”>\n’ +
    ‘<head>\n’ +
    ‘<meta charset=“utf-8”>\n’ +
    ‘<title>Error</title>\n’ +
    ‘</head>\n’ +
    ‘<body>\n’ +
    ‘<pre>Cannot POST //api/services/encrypt</pre>\n’ +
    ‘</body>\n’ +
    ‘</html>\n’
}
```

In our previous tests, we always used 
```bash
npm run cli publish metadata/simpleDownloadDataset.json false
```
(ie, publish without encryption)

It works fine with Provider/Aquarius, so something is broken in ocean-node.

**Comment by paulo-ocean** [comment]
i can take this one if that´s ok

**Comment by paulo-ocean** [comment]
by the way, i think the option without encryption is also not working:
`npm run cli publish metadata/simpleDownloadDataset.json false` anymore
i get some errors like on processor createOrUpdateDDO():
`Error processMetadataEvents: Error: no such account`
i think its completely broken right now

**Comment by paulo-ocean** [comment]
by the way, i think the option without encryption is also not working anymore:
`npm run cli publish metadata/simpleDownloadDataset.json false`
i get some errors like on processor createOrUpdateDDO():
`Error processMetadataEvents: Error: no such account`
i think its completely broken right now

**Comment by paulo-ocean** [comment]
btw, i added some extra info on the PR itself: [https://github.com/oceanprotocol/ocean-node/pull/255](https://github.com/oceanprotocol/ocean-node/pull/255)
