### ISSUE TITLE
Starting OceanNode -> Timeout Promise timed out after 60000 milliseconds

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-node#300]
Starting the node on Ubuntu machine:

```console
TimeoutError: Promise timed out after 60000 milliseconds
    at file:///home/ubuntu/ocean-node/node_modules/p-timeout/index.js:70:24
    at new Promise (<anonymous>)
    at pTimeout (file:///home/ubuntu/ocean-node/node_modules/p-timeout/index.js:48:25)
    at Object.gateway (file:///home/ubuntu/ocean-node/node_modules/@achingbrain/nat-port-mapper/dist/src/discovery/index.js:56:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UPNPClient.findGateway (file:///home/ubuntu/ocean-node/node_modules/@achingbrain/nat-port-mapper/dist/src/upnp/index.js:80:25)
    at async UPNPClient.externalIp (file:///home/ubuntu/ocean-node/node_modules/@achingbrain/nat-port-mapper/dist/src/upnp/index.js:59:25)
    at async UPnPNAT.mapIpAddresses (file:///home/ubuntu/ocean-node/node_modules/@libp2p/upnp-nat/dist/src/upnp-nat.js:78:54)
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => network: optimism_sepolia Start block 5421511 network height 8707412',
  timestamp: '2024-02-29 14:36:05'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'network: optimism_sepolia processing 100 blocks ...',
  timestamp: '2024-02-29 14:36:05'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => New last indexed block : 5421611',
  timestamp: '2024-02-29 14:36:06'
}

```

**Comment by alexcos20** [comment]
fixed in some upnp branch
