### ISSUE TITLE
Config - Parsing/reading process.env.RPCS variable can break if wrong JSON format 

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#419]
On the config we're not expecting a wrongly formatted JSON (not handling possible exception). We have :
```
function getSupportedChains(): RPCS {
  if (!process.env.RPCS || !JSON.parse(process.env.RPCS)) {
```
`JSON.parse(process.env.RPCS)` can throw an exception if the JSON is not correctly formatted and it breaks the node (does not start)

Also, it does not build at all (until we explicitly `unset RPCS`) since the dashboard build will also break with a wrong RPCS env setting:

```
211 packages are looking for funding
  run `npm fund` for details
   Linting and checking validity of types  ..
 ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
 ✓ Linting and checking validity of types    
   ▲ Next.js 14.0.4
   - Environments: .env

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Collecting page data  .SyntaxError: Unexpected token , in JSON at position 104
    at JSON.parse (<anonymous>)
    at 4261 (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:28961)
    at o (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:127)
    at /home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:23521
    at o.a (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:864)
    at 3877 (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:23360)
    at o (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:127)
    at /home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:33173
    at o.a (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:864)
    at 7229 (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:33059)

> Build error occurred
Error: Failed to collect page data for /
    at /home/paulo/workspace/OCEAN/ocean-node/dashboard/node_modules/next/dist/build/utils.js:1220:15 {
  type: 'Error'
}
```

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/420](https://github.com/oceanprotocol/ocean-node/pull/420)
