### ISSUE TITLE
Log tests randomly fail

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#620]
The log tests are failing (although not every time):

```
  93 passing (4m)
  1 failing

  1) LogDatabase CRUD
       should save a log in the database when a log.logMessage is called:

      AssertionError: expected +0 to equal 1
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (file:///home/runner/work/ocean-node/ocean-node/dist/test/integration/logs.test.js:72:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I haven't been able to replicate this locally, so far I've only seen it on the CI. 

It's also not always the same test that fails. For example, sometimes this test fails: 

```
110 passing (5m)
  1 failing

  1) LogDatabase retrieveMultipleLogs with pagination
       should retrieve logs for a specific page:

      AssertionError: expected '799' to not equal '799'
      + expected - actual


      at Context.<anonymous> (file:///home/runner/work/ocean-node/ocean-node/dist/test/integration/logs.test.js:273:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by paulo-ocean** [comment]
i'm gonna check these... i know how to fix the 1st one... haven't checked the 2nd
